version: '3.8'

services:
  web:
    build: .
    # command: gunicorn --bind 0.0.0.0:8000 ./core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - db

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_DB: nome_do_banco
#       POSTGRES_USER: usuario
#       POSTGRES_PASSWORD: senha

# volumes:
#   postgres_data:
